#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/common.sh"

PLATFORM="${PLATFORM:-virt-cortex-a53}"
BOOT_CHAIN="${BOOT_CHAIN:-linux}"   # linux | atf
CPU="$(yplat "${PLATFORM}" cpu)"
MACHINE="$(yplat "${PLATFORM}" machine)"
SMP="$(yplat "${PLATFORM}" smp)"
MEM_MB="$(yplat "${PLATFORM}" mem_mb)"

SERIAL_TELNET_PORT="${SERIAL_TELNET_PORT:-}"
SERIAL_TELNET_HOST="${SERIAL_TELNET_HOST:-127.0.0.1}"

QEMU_BIN="out/runtime/run-qemu-system-aarch64"

VMLINUX="${IMG_DIR}/Image"
INITRAMFS="${IMG_DIR}/rootfs.cpio.gz"
FLASH="${IMG_DIR}/flash.bin"         # generated by scripts/gen_flash.sh (BL1+FIP)
UBOOT_BIN="${IMG_DIR}/u-boot.bin"    # built by scripts/build_uboot.sh (optional check)

# Where to preload Linux artifacts in RAM (virt RAM typically starts at 0x40000000)
KERNEL_ADDR="${KERNEL_ADDR:-0x40200000}"
INITRD_ADDR="${INITRD_ADDR:-0x44000000}"

if [[ ! -x "${QEMU_BIN}" ]]; then
  echo "ERROR: QEMU not built: ${QEMU_BIN}" >&2
  exit 1
fi

# Validate CPU exists in this QEMU build
if ! "${QEMU_BIN}" -cpu help | grep -qE "(^|[[:space:]])${CPU}([[:space:]]|$)"; then
  echo "ERROR: CPU '${CPU}' not supported by this QEMU build." >&2
  "${QEMU_BIN}" -cpu help | head -n 120 >&2 || true
  exit 2
fi

QEMU_ARGS=(
  -cpu "${CPU}" -smp "${SMP}" -m "${MEM_MB}"
  -nographic
  -no-reboot
)

# Serial config
if [[ -n "${SERIAL_TELNET_PORT}" ]]; then
  QEMU_ARGS+=(-serial "telnet:${SERIAL_TELNET_HOST}:${SERIAL_TELNET_PORT},server,nowait")
else
  # good default for interactive CI/tmate mode
  QEMU_ARGS+=(-serial mon:stdio)
fi

if [[ "${BOOT_CHAIN}" == "atf" ]]; then
  # TF-A (BL1) + FIP (BL2/BL31 + U-Boot as BL33) in flash.bin
  if [[ ! -f "${FLASH}" ]]; then
    echo "ERROR: missing ${FLASH}. Run: scripts/build_uboot.sh && scripts/build_atf.sh && scripts/gen_flash.sh" >&2
    exit 1
  fi
  if [[ ! -f "${VMLINUX}" || ! -f "${INITRAMFS}" ]]; then
    echo "ERROR: missing Linux images (${VMLINUX}, ${INITRAMFS}). Run: PLATFORM=${PLATFORM} bash scripts/build_all.sh" >&2
    exit 1
  fi

  # IMPORTANT: secure=on is required for TF-A chain on virt
  # Note: we intentionally DO NOT pass -kernel/-initrd/-append here.
  # We preload Image/initramfs into RAM, and U-Boot will booti them.
  QEMU_ARGS+=(
    -machine virt,secure=on
    -bios "${FLASH}"
    -device "loader,file=${VMLINUX},addr=${KERNEL_ADDR}"
    -device "loader,file=${INITRAMFS},addr=${INITRD_ADDR}"
  )

  INITRD_SIZE_DEC="$(stat -c%s "${INITRAMFS}")"
  INITRD_SIZE_HEX="$(printf '0x%x' "${INITRD_SIZE_DEC}")"

  echo "[run_qemu] BOOT_CHAIN=atf"
  echo "[run_qemu] Kernel preloaded @ ${KERNEL_ADDR}"
  echo "[run_qemu] Initramfs preloaded @ ${INITRD_ADDR}"
  echo "[run_qemu] In U-Boot, run:"
  echo "  setenv bootargs 'console=ttyAMA0 earlycon rdinit=/init panic=-1'"
  echo "  booti ${KERNEL_ADDR} ${INITRD_ADDR}:${INITRD_SIZE_HEX} \${fdtcontroladdr}"
else
  # Direct Linux boot (your current flow)
  if [[ ! -f "${VMLINUX}" || ! -f "${INITRAMFS}" ]]; then
    echo "ERROR: missing images. Run: PLATFORM=${PLATFORM} bash scripts/build_all.sh" >&2
    exit 1
  fi

  QEMU_ARGS+=(
    -M "${MACHINE}"
    -kernel "${VMLINUX}"
    -initrd "${INITRAMFS}"
    -append "console=ttyAMA0 earlycon=pl011,0x09000000 rdinit=/init panic=-1"
  )

  echo "[run_qemu] BOOT_CHAIN=linux (direct)"
fi

exec "${QEMU_BIN}" "${QEMU_ARGS[@]}"
